# Generated by Django 3.0.3 on 2020-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula8', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AddField(
            model_name='pet',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
