BBBBBBB BBBBBBBBBBB
BBBBB BBBBB
XXXXXX XX XXXX XX
BBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XX XXXXX

XXXXXXXXXX
    XXXXXXXXXXXXX XX XXXXXXXXXXXXXX
    XXXX
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXX
        BBBBBB
    XXXXX
XXXXXXXXXXX
BBBBBBBB