# Generated by Django 3.0.3 on 2020-02-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aula5", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contanto", new_name="Contato",),
    ]
