# Generated by Django 3.0.3 on 2020-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aula11", "0002_post_publicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="deletado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="deletado_em",
            field=models.DateTimeField(null=True),
        ),
    ]
