# Generated by Django 3.0.3 on 2020-03-21 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aula11", "0005_destinatatio_remetente"),
    ]

    operations = [
        migrations.CreateModel(
            name="TecnologiaPost",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("aula11.post",),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.DateField(blank=True)),
                ("twitter", models.CharField(blank=True, max_length=60)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
