# Generated by Django 3.0.3 on 2020-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aula11", "0007_auto_20200321_1408"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automovel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=30)),
                ("modelo", models.CharField(max_length=30)),
                ("slug", models.CharField(max_length=100)),
            ],
        ),
    ]
